[package]
name = "ch22-core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
wasm-bindgen = "0.2.99"
console_error_panic_hook = { version = "0.1.7", optional = true }

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]
